# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SwcDVEUfHN1gfhUKptGcclTxrgVABUM
"""

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

import requests

image = Image.open(requests.get('https://a57.foxnews.com/media.foxbusiness.com/BrightCove/854081161001/201805/2879/931/524/854081161001_5782482890001_5782477388001-vs.jpg', stream=True).raw)

image.resize((350,250))
imagearr = np.array(image)
image

grey_image = cv2.cvtColor(imagearr,cv2.COLOR_BGR2GRAY)
Image.fromarray(grey_image)

noise_reduced_image = cv2.GaussianBlur(grey_image,(5,5),0)
Image.fromarray(noise_reduced_image)

dilated_image = cv2.dilate(noise_reduced_image,np.ones((3,3)))
Image.fromarray(dilated_image)

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3))
closeing = cv2.morphologyEx(dilated_image,cv2.MORPH_ELLIPSE,kernel)
Image.fromarray(closeing)

car_cascade_src = 'cars.xml'
car_cascade = cv2.CascadeClassifier(car_cascade_src)
cars = car_cascade.detectMultiScale(closeing, 1.1, 1)

cnt = 0
for (x,y,w,h) in cars:
  cv2.rectangle(imagearr,(x,y),(x+w,y+h),(255,0,0),2)
  cnt += 1
print(cnt, " cars found")
Image.fromarray(imagearr)

image2 = Image.open(requests.get('https://qph.fs.quoracdn.net/main-qimg-b5c4e39dcd48dddd9e609e6022f74d85', stream=True).raw)
image2 = image2.resize((450,250))
image_arr2 = np.array(image2)
grey2 = cv2.cvtColor(image_arr2,cv2.COLOR_BGR2GRAY)

bus_cascade_src = 'Bus_front.xml'
bus_cascade = cv2.CascadeClassifier(bus_cascade_src)
bus = bus_cascade.detectMultiScale(grey2, 1.1, 1)

cnt = 0
for (x,y,w,h) in bus:
  cv2.rectangle(image_arr2,(x,y),(x+w,y+h),(255,0,0),2)
  cnt += 1
print(cnt, " bus's found")
Image.fromarray(image_arr2)

cascade_src = 'cars.xml'
video_src = 'Cars.mp4'

cap = cv2.VideoCapture(video_src)
car_cascade = cv2.CascadeClassifier(cascade_src)
video = cv2.VideoWriter('result.avi',cv2.VideoWriter_fourcc(*'DIVX'), 15, (450,250))

while True:
    ret, img = cap.read()

    if (type(img) == type(None)):
        break

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cars = car_cascade.detectMultiScale(gray, 1.1, 2)

    for (x,y,w,h) in cars:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)

    video.write(img)
video.release()